---
- name: Stop VM
  community.vmware.vmware_guest:
    datacenter: Shadowman-DC
    cluster: Cluster01
    name: "{{ template_name }}"
    state: poweredoff
    validate_certs: false

- name: Convert to Template
  community.vmware.vmware_guest:
    datacenter: Shadowman-DC
    cluster: Cluster01
    name: "{{ template_name }}"
    is_template: true
    validate_certs: false
