---
- name: Perform VM removal pre-steps
  hosts: "{{ vm_name }}"
  gather_facts: false

  tasks:
    - name: Delete Windows host from AD
      microsoft.ad.computer:
        name: "{{ fqdn.split('.')[0] }}"
        state: absent
      delegate_to: "dc01.ad.shadowman.dev"
