---
# - name: RHV Hostname
#   ansible.builtin.include_tasks: rhv_hostname.yml
#   when: shadowman_provision_hypervisor == "RHV"

# - name: Terraform Hostname
#   ansible.builtin.include_tasks: rhv_hostname.yml
#   when: shadowman_provision_hypervisor == "Terraform"

- name: VMWare Hostname
  ansible.builtin.include_tasks: vmware_hostname.yml
  when: shadowman_provision_hypervisor == "VMWare"
